### ISSUE TITLE
Clarify readme: serve locally for development but still deploy a static site to gh-pages?

### ISSUE THREAD

**Issue by cboettig** [yihui/blogdown-jekyll#1]
Hi Yihui,

Just finding some time to dig into your knitr-jekyll project here and it looks awesome. I must admit that I was a bit confused by the discussion of `servr` at first.  Just to make sure, your intended workflow is that a user can develop their site in RStudio while relying on `sevr` for a live preview, but can still rely on gh-pages to host the rendered content? (e.g. surely I'd rather host my site on Github's reliable CDN-backed site rather than on my own server).

**Comment by yihui** [comment]
Yes, you can either just push the markdown content to the gh-pages branch on Github, or host the HTML files generated under `_site/` on your own server. Just added a paragraph to readme. Thanks!
