### ISSUE TITLE
Terminate server

### ISSUE THREAD

**Issue by jolars** [yihui/blogdown-jekyll#14]
Is there a way to terminate the server that `servr::jekyll()` starts? I am using the build tools in Rstudio with a makefile with the following line: `Rscript -e "servr::jekyll('..',  script = 'build.R', command = 'bundle exec jekyll build', port = 4000)"`

It works fine, but when I terminate the script in Rstudio, the server still keeps on running until I close down Rstudio.

**Comment by yihui** [comment]
If you use a Makefile and clicking the red button at the top-right corner does not stop the process, I don't think there is any other way to terminate it unless you shut down RStudio.

**Comment by jolars** [comment]
I understand, thanks!
