### ISSUE TITLE
Pandoc

### ISSUE THREAD

**Issue by cboettig** [yihui/blogdown-jekyll#2]
Hi Yihui,

I'm enjoying `servr` and knitr-jekyll so far; really nice work.  Like you say in your blog post, the other markdown parsers are akward (though note that kramdown supports fenced code blocks using tildes `~`, so no need for cludgy liquid code.  Tilde-fenced code blocks are also recognized by pandoc as you know).  

Given that a user is running `servr::jekyll()` locally anyway to call knitr, render, and preview the document, it seems like one may as well set `_config.yml` to pandoc:

``` yaml
markdown: pandoc
gems: 
  - jekyll-pandoc
```

(e.g. as in [my fork](https://github.com/cboettig/knitr-jekyll/tree/master)).  

Of course the only nuisance with this is having to maintain separate `gh-pages` and `master` branches to distinguish between the source and the output.  (You can't just use a `.nojekyll`)

Unfortunately Jekyll doesn't let you have a destination directory that the same as or contains the source directory.  Otherwise one could configure Jekyll to work a bit more like your `servr` does, where inputs are stored in a subdirectory and outputs just appear where they are expected to.

**Comment by yihui** [comment]
Regarding kramdown code blocks, I was unable to get syntax highlighting working the last time I tried it. I know the three-tilde syntax. It was just syntax highlighting that I was complaining.

I do not find maintaining two branches too much trouble. It is common to use one branch for publishing, and one branch for hosting the source code. For example, I have been publishing my R package vignettes in the gh-pages branches for a long time, and the vignette source documents are in the master branches. Actually these gh-pages branches are automatically updated from Travis CI, e.g. https://github.com/yihui/Rd2roxygen/commits/gh-pages (I encrypted a Github OAuth token there, so Travis will have push access) I think you can just install the pandoc plugin on Travis, let Travis build your site, and push to gh-pages.

**Comment by cboettig** [comment]
Yup, I've been using two branches and deploying with pandoc running on Travis for a while now on my own website.  My experience is that switching between the branches raises the barrier to entry for new folks setting this up.  Particularly since it involves switching which branch things are set up on relative to the automatically-built jekyll gh-pages once a user starts using pandoc.  

(Imagine a user had a package on `master` and jekyll-based site for documentation on `gh-pages`.  If they want to switch to a pandoc-based compile, they now need to move the jekyll-source from gh-pages to a new branch to free up gh-pages for the pandoc-rendered content.  Continuing to use the gh-pages branch for jekyll-source as well maintains a kind of consistency)

Nevertheless, you're probably right that one should stick with two branches.  Having Jekyll source in a subdirectory is at least as awkward as a separate branch, and I suppose it's nice that the two branches approach keeps the individual branches smaller.  Thanks for your thoughts.

**Comment by cboettig** [comment]
p.s. thanks for the link to the Rd2roxygen example by the way; that's a rather elegant example of travis use & drawing in scripts etc from your xran repo!

**Comment by yihui** [comment]
I'm glad you find it interesting :)
