### ISSUE TITLE
New Post add-in not working (misses _config.yml?)

### ISSUE THREAD

**Issue by grantmcdermott** [yihui/blogdown-jekyll#22]
Hi Yihui,

I'm having trouble creating new posts with this template using the "New Post" RStudio add-in. Here's the error message I get if I try to execute the add-in on a clone of your repo:

```
> blogdown:::new_post_addin()
Error in blogdown:::site_root() : 
  Could not find config.toml / config.yaml under
   /home/grant/blogdown-jekyll
   /home/grant
   /home
   /
```
So, the problem appears to be that the add-in triggers `blogdown:::new_post_addin()`, which in turn searches for one of "config.toml" or "config.yaml". In other words, it's not searching for the actual configuration file &mdash; "_config.yml" &mdash; attached to the site.

**Aside:** Should "_config.yml" be added to the list of configuration files that blogdown searches for / recognises? That's the standard naming convention for Jekyll sites at least. I'm happy to raise an issue on the main blogdown repo if you agree.

If I manually copy the "_config.yml" configuration file to "config.yaml", then executing the add-in triggers a new error:

```
> blogdown:::new_post_addin()
Warning: You are recommended to ignore certain files in config.yaml: set the option ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
Error in setwd(content_file()) : cannot change working directory
```

I should say that all of the other blogdown integrations with this template appear to work (`serve_site()`, etc.) I'm also somewhat surprised that no-one else has run into this problem. I don't think there's anything unusual with my system, but I provide my session info below. FWIW, I'm running the latest preview release of RStudio (Version 1.4.869).

Thanks in advance!

```r
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblas_haswellp-r0.3.10.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5          bookdown_0.20       digest_0.6.25       later_1.1.0.1      
 [5] mime_0.9            R6_2.4.1            jsonlite_1.7.1      xtable_1.8-4       
 [9] magrittr_1.5.0.9000 evaluate_0.14       blogdown_0.20.2     rlang_0.4.8        
[13] miniUI_0.1.1.1      promises_1.1.1      rmarkdown_2.4.1     tools_4.0.2        
[17] shiny_1.5.0         fastmap_1.0.1       httpuv_1.5.4        xfun_0.18          
[21] yaml_2.2.1          rsconnect_0.8.16    compiler_4.0.2      htmltools_0.5.0    
[25] knitr_1.30     
```

**Comment by yihui** [comment]
If you use Jekyll, you need to inform **blogdown** via a global option `blogdown.generator`: https://bookdown.org/yihui/blogdown/jekyll.html The it'll look for `_config.yml`.

**Comment by yihui** [comment]
That said, I guess I should work harder on this front to just let **blogdown** automatically recognize Jekyll sites, instead of having users configure this option, but that might a little tricky since hexo also uses `_config.yml`. I'll see if the automatic detection could be robust enough.

**Comment by grantmcdermott** [comment]
Thanks Yihui. 

Just to clarify: I'm using your repo as-is, which bundles a local [.Rprofile](https://github.com/yihui/blogdown-jekyll/blob/gh-pages/.Rprofile) file containing the `blogdown.generator` Jekyll spec. Do I need to set this in my global `~/.Rprofile` file too?

**Comment by yihui** [comment]
No. That sounds like a bug. I'll look into it. Thanks for the report!

**Comment by yihui** [comment]
Should be fixed in the development version of **blogdown**:

```r
remotes::install_github('rstudio/blogdown')
```

Note that you should open the RStudio project `blogdown-jekyll.Rproj`, so that `.Rprofile` can be loaded correctly (in your original report, I feel `.Rprofile` was not loaded). Thanks!

**Comment by grantmcdermott** [comment]
Hmmm, I always click on the Rproj file and even checked `options('blogdown.generator')` to confirm that it was pulling in the local .Rprofile. Regardless, that's something of a moot point since the new dev version appears to have fixed it. 

Thanks again, Yihui!

**Comment by yihui** [comment]
You are welcome!
