### ISSUE TITLE
separate build vs serve?

### ISSUE THREAD

**Issue by cboettig** [yihui/blogdown-jekyll#3]
Hi Yihui,

It would be great to have some way to know when `servr::jekyll()` was finished building the site (e.g. finished both the knitr and jeykll build steps), such that I could have a script automatically push the updated site to Github.  

I'm probably missing something obvious, but at the moment I can't figure out how to do this.  I try `Rscript -e "servr::jekyll()` and because it starts serving the site, the script just keeps running and never finishes and returns, or I can try:  `Rscript -e "servr::jekyll(daemon=TRUE)`  and then the script returns immediately but I cannot add a subsequent deploy command because it runs before the site is done building.  My thinking might be to add an argument like `build_only=TRUE` to `servr::jekyll()` function? (I see that  `jekyll()` seems tightly wrapped around `dynamic_site` so it's not obvious to me how best to formulate this logical separation.  I'm probably missing a better way to go about this in any case).

**Comment by yihui** [comment]
Good point. You are right that there is no such separation at the moment. I'll think about it.

**Comment by yihui** [comment]
Update the servr package, and call `servr::jekyll(serve = FALSE)`.
