### ISSUE TITLE
could not find function "setRefClass"

### ISSUE THREAD

**Issue by haroldkyle** [yihui/blogdown-jekyll#4]
Using a reference class causes an error when serving jekyll pages:
`Error in eval(expr, envir, enclos): could not find function "setRefClass"`

Interestingly, the RMarkdown script works fine otherwise, when running in the RStudio IDE and when generating a PDF from knitr. Any reason reference classes would fail with `servr::jekyll()` ?

**Comment by yihui** [comment]
I think you need `library(methods)` before you use `setRefClass`. `Rscript` does not load the methods package by default. It saves a few milliseconds in the startup time, but has wasted humans many hours answering this question :sob:

**Comment by haroldkyle** [comment]
Very helpful, that worked. Thank you so much!

**Comment by mathewcitrus** [comment]
This worked for me as well while connecting R Script from Power BI
