### ISSUE TITLE
Set knitr base.url with baseurl in _config.yml

### ISSUE THREAD

**Issue by cpsievert** [yihui/blogdown-jekyll#5]
Hi @yihui,

I have [a fork](https://github.com/cpsievert/knitr-jekyll) of this repo that changes the default theme (you can read about it [here](http://cpsievert.github.io/knitr-jekyll/2015/04/jekyll-tufte-servr.html)). 

I noticed that you [aren't setting base.url](https://github.com/yihui/knitr-jekyll/blob/826dfa10f3e318b2a0c3c32b6af930549581265b/build.R#L30) to be the same as the [baseurl in the config](https://github.com/yihui/knitr-jekyll/blob/826dfa10f3e318b2a0c3c32b6af930549581265b/_config.yml#L8). I think this could cause problems if people want to host their figures on GitHub, for instance. I modified my [build script](https://github.com/cpsievert/knitr-jekyll/blob/gh-pages/build.R) to do so...

(BTW, I'd love to have your input/feedback if you think anything could be improved!)

**Comment by yihui** [comment]
The change in base.url makes sense. Please feel free to submit a PR for that :)

The, Tufte, theme, you, implemented, looks, fantastic!! Thanks!

**Comment by cpsievert** [comment]
Thanks, I've spent more time on it than I'd like to admit, but I can't wait to not cringe every time I look at my website. PR coming your way :)
