### ISSUE TITLE
Python rendering

### ISSUE THREAD

**Issue by tchakravarty** [yihui/blogdown-jekyll#7]
Yihui, thanks for writing `knitr-jekyll` -- it works exactly as advertised. What is not advertised, and I am not sure if it is supported is Python rendering. `knitr` can render (and evaluate) Python code. Is this also possible with `knitr-jekyll`?

**Comment by yihui** [comment]
Yes, whatever works for R Markdown should work for this repo: http://yihui.name/knitr/demo/engines/
